cc_binary(
    name = "haar",
    srcs = ["haar.cc"],
    deps = [
        "@opencv//:opencv"
    ],
)

cc_binary(
    name = "temp_matching",
    srcs = ["modified_template_matching.cc"],
    deps = [
        "@opencv//:opencv"
    ],
)

cc_binary(
    name = "tm_sobel",
    srcs = ["sobel_plus_tm.cc"],
    deps = [
        "@opencv//:opencv"
    ],
)
